export const SET_MECHANIC_PROFILE = 'SET_MECHANIC_PROFILE';
export const SET_MECHANIC_SERVICES = 'SET_MECHANIC_SERVICES';
export const SET_MECHANIC_SERVICES_META = 'SET_MECHANIC_SERVICES_META';
export const CLEAR_MECHANIC_SERVICES = 'CLEAR_MECHANIC_SERVICES';
export const CLEAR_MECHANIC_SERVICES_META = 'CLEAR_MECHANIC_SERVICES_META';
