export const SET_FULFILLED_JOBS = 'SET_FULFILLED_JOBS';
export const SET_FULFILLED_JOBS_META = 'SET_FULFILLED_JOBS_META';
export const SET_UNFULFILLED_JOBS = 'SET_UNFULFILLED_JOBS';
export const SET_UNFULFILLED_JOBS_META = 'SET_UNFULFILLED_JOBS_META';
